local Constants = {}

-- TODO add a ton from the std::library
Constants.cpp_keywords = {
  "alignas", "alignof", "and", "and_eq", "asm", "auto", "bitand", "bitor",
  "bool", "break", "case", "catch", "char", "char16_t", "char32_t", "char8_t",
  "class", "co_await", "co_return", "co_yield", "compl", "concept", "const",
  "const_cast", "consteval", "constexpr", "constinit", "continue", "decltype",
  "default", "define", "delete", "do", "double", "dynamic_cast", "else",
  "enum", "explicit", "export", "extern", "final", "float", "for", "friend",
  "goto", "if", "import", "include", "inline", "int", "long", "module",
  "mutable", "namespace", "new", "noexcept", "not", "not_eq", "nullptr",
  "operator", "or", "or_eq", "override", "pragma", "private", "protected",
  "public", "register", "reinterpret_cast", "requires", "return", "short",
  "signed", "sizeof", "static", "static_assert", "static_cast", "struct",
  "switch", "template", "this", "thread_local", "throw", "try", "typedef",
  "typeid", "typename", "union", "unsigned", "using", "virtual", "void",
  "volatile", "wchar_t", "while", "xor", "xor_eq",
}

-- TODO add common constructions, function signatures (with generics)
Constants.go_keywords = {
  "append", "bool", "break", "byte", "cap", "case", "chan", "close", "complex",
  "const", "continue", "copy", "default", "defer", "delete", "else", "error",
  "fallthrough", "float", "for", "func", "go", "goto", "if", "imag", "import",
  "int", "interface", "iota", "len", "make", "map", "nil", "package", "panic",
  "print", "println", "range", "real", "recover", "return", "rune", "select",
  "string", "struct", "switch", "type", "uint", "uintptr", "var",
}

-- TODO get some rust zealot to add more rusty words
Constants.rust_keywords = {
  "Self", "abstract", "alignof", "as", "assert", "assert_approx_eq",
  "assert_eq", "become", "bool", "box", "break", "char", "const", "continue",
  "crate", "dbg", "do", "else", "enum", "eprint", "eprintln", "extern",
  "final", "fn", "for", "format", "if", "impl", "in", "isize", "let", "loop",
  "macro", "macro_rules", "match", "mod", "move", "mut", "offsetof",
  "override", "panic", "print", "println", "priv", "pub", "pure", "ref",
  "return", "self", "sizeof", "static", "str", "struct", "super", "trait",
  "type", "typeof", "union", "unsafe", "unsized", "use", "usize", "virtual",
  "where", "while", "yield",
}

-- TODO add words from numpy, pandas, matplotlib, and more great libraries.
Constants.python_keywords = {
  "None", "abs", "all", "and", "any", "as", "ascii", "assert", "async",
  "await", "bin", "bool", "break", "bytearray", "bytes", "callable", "case",
  "chr", "class", "classmethod", "compile", "complex", "continue", "def",
  "del", "delattr", "dict", "dir", "divmod", "elif", "else", "enumerate",
  "eval", "except", "exec", "file", "filter", "finally", "float", "for",
  "format", "from", "frozenset", "getattr", "global", "globals", "hasattr",
  "hash", "help", "hex", "id", "if", "import", "in", "input", "int", "is",
  "isinstance", "issubclass", "iter", "lambda", "len", "list", "locals", "map",
  "match", "max", "memoryview", "min", "next", "not", "object", "oct", "open",
  "or", "ord", "pass", "pow", "print", "property", "raise", "range", "repr",
  "return", "reversed", "round", "set", "setattr", "slice", "sorted",
  "staticmethod", "str", "sum", "super", "try", "tuple", "type", "vars",
  "while", "with", "yield", "zip",
}

-- TODO not sure, what is lua even, never heard of it
Constants.lua_keywords = {
  "_G", "_VERSION", "and", "arg", "assert", "break", "collectgarbage",
  "coroutine", "debug", "do", "dofile", "else", "elseif", "end", "error",
  "for", "function", "getmetatable", "goto", "if", "in", "io", "ipairs",
  "load", "loadfile", "local", "math", "next", "nil", "not", "or", "os",
  "package", "pairs", "pcall", "print", "rawequal", "rawget", "rawlen",
  "rawset", "repeat", "require", "return", "select", "setmetatable", "string",
  "table", "then", "tonumber", "tostring", "type", "until", "utf8", "warn",
  "while", "xpcall",
}

-- TODO make a top 1000 most uncommon english words as well
Constants.english_common = {
  "as", "I", "his", "that", "he", "was", "for", "on", "are", "with", "they",
  "be", "at", "one", "have", "this", "from", "by", "hot", "word", "but",
  "what", "some", "is", "it", "you", "or", "had", "the", "of", "to", "and",
  "a", "in", "we", "can", "out", "other", "were", "which", "do", "their",
  "time", "if", "will", "how", "said", "an", "each", "tell", "does", "set",
  "three", "want", "air", "well", "also", "play", "small", "end", "put",
  "home", "read", "hand", "port", "large", "spell", "add", "even", "land",
  "here", "must", "big", "high", "such", "follow", "act", "why", "ask", "men",
  "change", "went", "light", "kind", "off", "need", "house", "picture", "try",
  "us", "again", "animal", "point", "mother", "world", "near", "build", "self",
  "earth", "father", "any", "new", "work", "part", "take", "get", "place",
  "made", "live", "where", "after", "back", "little", "only", "round", "man",
  "year", "came", "show", "every", "good", "me", "give", "our", "under",
  "name", "very", "through", "just", "form", "sentence", "great", "think",
  "say", "help", "low", "line", "differ", "turn", "cause", "much", "mean",
  "before", "move", "right", "boy", "old", "too", "same", "she", "all",
  "there", "when", "up", "use", "your", "way", "about", "many", "then", "them",
  "write", "would", "like", "so", "these", "her", "long", "make", "thing",
  "see", "him", "two", "has", "look", "more", "day", "could", "go", "come",
  "did", "number", "sound", "no", "most", "people", "my", "over", "know",
  "water", "than", "call", "first", "who", "may", "down", "side", "been",
  "now", "find", "head", "stand", "own", "page", "should", "country", "found",
  "answer", "school", "grow", "study", "still", "learn", "plant", "cover",
  "food", "sun", "four", "between", "state", "keep", "eye", "never", "last",
  "let", "thought", "city", "tree", "cross", "farm", "hard", "start", "might",
  "story", "saw", "far", "sea", "draw", "left", "late", "run", "don’t",
  "while", "press", "close", "night", "real", "life", "few", "north", "book",
  "carry", "took", "science", "eat", "room", "friend", "began", "idea", "fish",
  "mountain", "stop", "once", "base", "hear", "horse", "cut", "sure", "watch",
  "color", "face", "wood", "main", "open", "seem", "together", "next", "white",
  "children", "begin", "got", "walk", "example", "ease", "paper", "group",
  "always", "music", "those", "both", "mark", "often", "letter", "until",
  "mile", "river", "car", "feet", "care", "second", "enough", "plain", "girl",
  "usual", "young", "ready", "above", "ever", "red", "list", "though", "feel",
  "talk", "bird", "soon", "body", "dog", "family", "direct", "pose", "leave",
  "song", "measure", "door", "product", "black", "short", "numeral", "class",
  "wind", "question", "happen", "complete", "ship", "area", "half", "rock",
  "order", "fire", "south", "problem", "piece", "told", "knew", "pass",
  "since", "top", "whole", "king", "street", "inch", "multiply", "nothing",
  "course", "stay", "wheel", "full", "force", "blue", "object", "decide",
  "surface", "deep", "moon", "island", "foot", "system", "busy", "test",
  "record", "boat", "common", "gold", "possible", "plane", "stead", "dry",
  "wonder", "laugh", "thousand", "ago", "ran", "check", "game", "shape",
  "equate", "hot", "miss", "brought", "heat", "snow", "tire", "bring", "yes",
  "distant", "fill", "east", "paint", "language", "among", "unit", "power",
  "town", "fine", "certain", "fly", "fall", "lead", "cry", "dark", "machine",
  "note", "wait", "plan", "figure", "star", "box", "noun", "field", "rest",
  "correct", "able", "pound", "done", "beauty", "drive", "stood", "contain",
  "front", "teach", "week", "final", "gave", "green", "oh", "quick", "develop",
  "ocean", "warm", "free", "minute", "strong", "special", "mind", "behind",
  "clear", "tail", "produce", "fact", "space", "heard", "best", "hour",
  "better", "true", "during", "hundred", "five", "remember", "step", "early",
  "hold", "west", "ground", "interest", "reach", "fast", "verb", "sing",
  "listen", "six", "table", "travel", "less", "morning", "ten", "simple",
  "several", "vowel", "toward", "war", "lay", "against", "pattern", "slow",
  "center", "love", "person", "money", "serve", "appear", "road", "map",
  "rain", "rule", "govern", "pull", "cold", "notice", "voice", "energy",
  "hunt", "probable", "bed", "brother", "egg", "ride", "cell", "believe",
  "perhaps", "pick", "sudden", "count", "square", "reason", "length",
  "represent", "art", "subject", "region", "size", "vary", "settle", "speak",
  "weight", "general", "ice", "matter", "circle", "pair", "include", "divide",
  "syllable", "felt", "grand", "ball", "yet", "wave", "drop", "heart", "am",
  "present", "heavy", "dance", "engine", "position", "arm", "wide", "sail",
  "material", "fraction", "forest", "sit", "race", "window", "store", "summer",
  "train", "sleep", "prove", "lone", "leg", "exercise", "wall", "catch",
  "mount", "wish", "sky", "board", "joy", "winter", "sat", "written", "wild",
  "instrument", "kept", "glass", "grass", "cow", "job", "edge", "sign",
  "visit", "past", "soft", "fun", "bright", "gas", "weather", "month",
  "million", "bear", "finish", "happy", "hope", "flower", "clothe", "strange",
  "gone", "trade", "melody", "trip", "office", "receive", "row", "mouth",
  "exact", "symbol", "die", "least", "trouble", "shout", "except", "wrote",
  "seed", "tone", "join", "suggest", "clean", "break", "lady", "yard", "rise",
  "bad", "blow", "oil", "blood", "touch", "grew", "cent", "mix", "team",
  "wire", "cost", "lost", "brown", "wear", "garden", "equal", "sent", "choose",
  "fell", "fit", "flow", "fair", "bank", "collect", "save", "control",
  "decimal", "ear", "else", "quite", "broke", "case", "middle", "kill", "son",
  "lake", "moment", "scale", "loud", "spring", "observe", "child", "straight",
  "consonant", "nation", "dictionary", "milk", "speed", "method", "organ",
  "pay", "age", "section", "dress", "cloud", "surprise", "quiet", "stone",
  "tiny", "climb", "cool", "design", "poor", "lot", "experiment", "bottom",
  "key", "iron", "single", "stick", "flat", "twenty", "skin", "smile",
  "crease", "hole", "jump", "baby", "eight", "village", "meet", "root", "buy",
  "raise", "solve", "metal", "whether", "push", "seven", "paragraph", "third",
  "shall", "held", "hair", "describe", "cook", "floor", "either", "result",
  "burn", "hill", "safe", "cat", "century", "consider", "type", "law", "bit",
  "coast", "copy", "phrase", "silent", "tall", "sand", "soil", "roll",
  "temperature", "finger", "industry", "value", "fight", "lie", "beat",
  "excite", "natural", "view", "sense", "capital", "won’t", "chair", "danger",
  "fruit", "rich", "thick", "soldier", "process", "operate", "practice",
  "separate", "difficult", "doctor", "please", "protect", "noon", "crop",
  "modern", "element", "hit", "student", "corner", "party", "supply", "whose",
  "locate", "ring", "character", "insect", "caught", "period", "indicate",
  "radio", "spoke", "atom", "human", "history", "effect", "electric", "expect",
  "bone", "rail", "imagine", "provide", "agree", "thus", "gentle", "woman",
  "captain", "guess", "necessary", "sharp", "wing", "create", "neighbor",
  "wash", "bat", "rather", "crowd", "corn", "compare", "poem", "string",
  "bell", "depend", "meat", "rub", "tube", "famous", "dollar", "stream",
  "fear", "sight", "thin", "triangle", "planet", "hurry", "chief", "colony",
  "clock", "mine", "tie", "enter", "major", "fresh", "search", "send",
  "yellow", "gun", "allow", "print", "dead", "spot", "desert", "suit",
  "current", "lift", "rose", "arrive", "master", "track", "parent", "shore",
  "division", "sheet", "substance", "favor", "connect", "post", "spend",
  "chord", "fat", "glad", "original", "share", "station", "dad", "bread",
  "charge", "proper", "bar", "offer", "segment", "slave", "duck", "instant",
  "market", "degree", "populate", "chick", "dear", "enemy", "reply", "drink",
  "occur", "support", "speech", "nature", "range", "steam", "motion", "path",
  "liquid", "log", "meant", "quotient", "teeth", "shell", "neck", "oxygen",
  "sugar", "death", "pretty", "skill", "women", "season", "solution", "magnet",
  "silver", "thank", "branch", "match", "suffix", "especially", "fig",
  "afraid", "huge", "sister", "steel", "discuss", "forward", "similar",
  "guide", "experience", "score", "apple", "bought", "led", "pitch", "coat",
  "mass", "card", "band", "rope", "slip", "win", "dream", "evening",
  "condition", "feed", "tool", "total", "basic", "smell", "valley", "nor",
  "double", "seat", "continue", "block", "chart", "hat", "sell", "success",
  "company", "subtract", "event", "particular", "deal", "swim", "term",
  "opposite", "wife", "shoe", "shoulder", "spread", "arrange", "camp",
  "invent", "cotton", "born", "determine", "quart", "nine", "truck", "noise",
  "level", "chance", "gather", "shop", "stretch", "throw", "shine", "property",
  "column", "molecule", "select", "wrong", "gray", "repeat", "require",
  "broad", "prepare", "salt", "nose", "plural", "anger", "claim", "continent",
}

return Constants
